name: Elm

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the Elm code
    runs-on: ubuntu-latest

    steps:
      - name: Set up the Elm environment
        uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Install `just`
        uses: extractions/setup-just@v2

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the Elm code base
        run: just build-elm

  test:
    name: Test the Elm code
    runs-on: ubuntu-latest

    steps:
      - name: Set up the Elm environment
        uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Install `just`
        uses: extractions/setup-just@v2

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Test the Elm code base
        run: just test
