name: Hygiene

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Install `just`
        uses: extractions/setup-just@v2

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the project
        run: just format-check
